### ISSUE TITLE
e621 author/artist bug

### ISSUE THREAD

**Issue by Danimus-Prime** [Simon-Tesla/RaccoonyWebEx#104]
**Describe the bug**
Each submission download would be saved in the "unknown_artist" folder with the same label being part of the filename

**To Reproduce**
1. Go to any e621 submission
2. Click on 'download'
3. See error

**Expected behavior**
Any submission with an artist tag should be placed in a artist's folder

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Latest version
 - Version of Raccoony: 1.2.4

**Comment by Simon-Tesla** [comment]
This might be a dup of #73, need to check whether the fix still repros with the current build or not. In any case I definitely need to spin up a new release, it's overdue. :P

**Comment by Eupeptic1** [comment]
I can repro this on e621, using my latest local version of Raccoony.

It doesn't seem to matter what kind of submission it is - my test bookmarks have a variety of file types (jpeg, webm, animated GIF, flash, animated PNG), but they all end up in the `unknown_artist` folder.

This _may be_ a change at e621; as recently as 25 July 2021 I downloaded some images from e621.  They were all sorted into the correct folder for the artist's name, and the the artist's name appears in the filename.

**Comment by Eupeptic1** [comment]
### Analysis

I _think_ e621 changed the wording in the `og:title` meta tag.  It used to say, in some cases, something like

`coolcritter drawn by coolartist1 - e621`

, but now it says

`coolcritter created by coolartist - e621`

.  The current e621 plugin is looking for that `drawn by` wording and failing to find it.

There are several different possible cases for that tag on e621 (see the long comment starting [here](https://github.com/Simon-Tesla/RaccoonyWebEx/blob/fbe0e800d6288cf321e48c31b453be927a2e0884/app/plugins/e621.ts#L48)), so they probably all need to be checked.

**Comment by Eupeptic1** [comment]
I think I have a fix.  Gist is [here](https://gist.github.com/Eupeptic1/e0f0634b4a74e9110965d4e7f0a9c5ae) - the meat of the change is this:

    84c81
    <         if(usernameElt && usernameElt.getAttribute('content').includes("created by ")) {
    ---
    >         if(usernameElt && usernameElt.getAttribute('content').includes("drawn by ")) {
    88c85
    <             let usernameStart = usernameplusjunk.lastIndexOf("created by ") + 11;
    ---
    >             let usernameStart = usernameplusjunk.lastIndexOf("drawn by ") + 9;

I also updated the comments (don't debug the comments) right above these lines to reflect the change.

#### Testing - small sample size

I first tested it with a list of 8 submissions at e621, that were specifically picked because they show different structures in e621's HTML.  I told Raccoony to auto-download and save metadata, opened those eight with the current (buggy) version, and observed that they all went to `e621/unknown_artist`, and all had `unknown_artist` in the filename.  I then cleaned out my download history, moved `Downloads/raccoony/e621` out of the way, loaded the proposed (bugfix) version, and opened those eight submissions again.

I observed that with the proposed version, the files went to a subdirectory of `e621` named for the artist.  One submission of those eight has no known artist at e621, so it still went to the `e621/unknown_artist`, which is correct.

I compared the results of the two runs with `fdupes` - all of the artwork files were binary equal.  The metadata files were also binary equal for the one submission with no known artist at e621.

I manually diffed the corresponding metadata files from the two runs, and the only changes were in the Author fields, in both the human-readable and JSON data.

I also did the following bulk comparison of the metadata files:

`find e621-before-unknown-artist-small e621-after-unknown-artist-small -iname "*txt" -exec cat {} \; | sort | uniq -c | sort -r -n`

and observed that the only lines that were not duplicated (n=1) were the human-readable and JSON Author fields for the submissions that have known artists at e621.

#### Testing - larger sample size

I felt like 8 submissions weren't quite enough, so I decided to make a list of everything I had personally downloaded from e621 lately, which came to 157 submissions.  These were not picked because they make good test cases; they were just images I liked.

I cleaned up my download history, moved `Downloads/raccoony/e621` out of the way, repeated the test with the buggy version of Raccoony, and observed that they all went to `e621/unknown_artist`, and all had `unknown_artist` in the filename.  There were also only 156 submissions downloaded - I investigated and found that one of the submissions I downloaded several weeks ago has since been deleted from e621.

I then cleaned out my download history, moved `Downloads/raccoony/e621` out of the way, loaded the proposed (bugfix) version, and opened those same 156 submissions again.

I observed that with the proposed version, the files went to a subdirectory of `e621` named for the artist.  Two submissions of those 156 have no known artist at e621, so they still went to `e621/unknown_artist`, which is correct.

I compared the results of the two runs with `fdupes` - all of the artwork files were binary equal.  The metadata files were also binary equal for the two submissions with no known artist at e621.

I did not manually diff the corresponding metadata files from the two runs.

I did do the following bulk comparison of the metadata files:

`find e621-before-unknown-artist-large e621-after-unknown-artist-large -iname "*txt" -exec cat {} \; | sort | uniq -c | sort -r -n`

and observed that the only lines that were not duplicated (n=1) were the human-readable and JSON Author fields for the submissions that have known artists at e621.

#### Conclusion

I think the proposed fix is working correctly.

**Comment by Simon-Tesla** [comment]
Fix checked in
