### ISSUE TITLE
Investigate using Google Noto raccoon emoji SVG in the UI instead of bitmaps

### ISSUE THREAD

**Issue by Simon-Tesla** [Simon-Tesla/RaccoonyWebEx#110]
While ScruffKerfluff's mascot is cute, it doesn't scale well to small sizes and is perhaps more visually complex than I'd like. Using something like the Google Noto emoji for raccoons would likely solve this issue.

![image](https://user-images.githubusercontent.com/2214046/132158452-47c7a055-4987-48ca-8550-3eb0e2a8d196.png)

[emoji_u1f99d.zip](https://github.com/Simon-Tesla/RaccoonyWebEx/files/7113192/emoji_u1f99d.zip)

In general we should look into using SVG files to replace the bitmap logos if that's supported, and SVG UI icons would also be nice.

Google Noto emojis are Apache 2.0-licenced which should be compatible with the MIT license. https://github.com/googlefonts/noto-emoji

The alternative to this would be to commission a logo, which I have considered, but there's a lot of complexity with figuring out the licensing that would be needed to be OSS-compliant.

**Comment by Eupeptic1** [comment]
> SVG UI icons would also be nice.

I already put this in an email a few months ago, but I figured I'd add it here, since it's related.

SVG UI icons would also remove a dependency on the user having the right fonts loaded on their machine.

Details: In 3/2021, I spun up a Debian 10 VM to test Raccoony in Chrome, Edge, and Firefox.  I had a very minimal Linux install, and when I first tried Raccoony, some of the glyphs on the buttons were missing.  Installing the "unifont" and "xfonts-unifont" packages in the OS fixed it; all of the glyphs appeared again in Raccoony.

Chrome: "open in tabs" lacked the two-boxes glyph; "fullscreen" lacked the magnifying-glass glyph; "open folder" lacked the file-folder glyph.  All of these had a hollow box instead of the glyph.  The other buttons were OK.

Edge: I don't remember exactly but *some* of the glyphs were missing and some were OK.

Firefox: "open in tabs" lacked the two-boxes glyph, but had "29C9" in a box instead.  The other buttons were OK.

**Comment by Simon-Tesla** [comment]
Yeah, I've wanted to replace those icons for a while as I know relying on system-installed fonts is never a great idea, just haven't gotten around to it. It should be relatively straightforward with SVGs at least; should be able to just inline SVG files right into the UI controls.
