### ISSUE TITLE
[Firefox] Open in Tabs changes focus...

### ISSUE THREAD

**Issue by momoe** [Simon-Tesla/RaccoonyWebEx#145]
I'm not sure if this is a RaccoonyWX setting or a Firefox browser setting (using a fresh browser install) however whenever I "Open All in Tabs" the browser immediately switches focus to the first opened one which is tripping up my process flow. 

If it's a browser setting please point me towards the preference or about:config.

**Comment by Simon-Tesla** [comment]
What version of Raccoony does it list you as having? If you're using version 1.2.6pre, that is an intentional change but you should be able to toggle it off in the extension global settings. I may change it to be an off-by-default setting before release.

(Also, if you're using 1.2.6pre, did you upgrade manually, or did you automatically get it? It shouldn't have auto-upgraded to that version.)

**Comment by momoe** [comment]
1.2.6pre is my version, and It's the first thing I manually added in my fresh Firefox install, after reading original Raccoony is going obsolete

**Comment by Simon-Tesla** [comment]
Ah, got it. Yeah, I marked that as a pre-release version, as there are a few things that aren't completely baked, but it should still work well enough.
