### ISSUE TITLE
deviantArt "siteFilename" uses the database index.

### ISSUE THREAD

**Issue by ChakatFirepaw** [Simon-Tesla/RaccoonyWebEx#34]
**Describe the bug**
On most dA submissions, triggering a save that uses siteFilename results in the save using the database index rather than the actual filename.

**To Reproduce**

Go to:
https://www.deviantart.com/cryptid-creations/art/Daily-Paint-2283-Merit-Badger-786557305
and trigger a download with {siteFilename} as part of the download path setting.

Resultant file is named dd0ani1-f433496a-1567-4553-9ff8-21c478482fe5.png

**Expected behavior**

Having the actual filename extracted, (daily_paint_2283__merit_badger_by_cryptid_creations_dd0ani1.png in this case), or going to a fallback of either filenameExt or using the page filename, (Daily-Paint-2283-Merit-Badger-786557305 in this case).

**Environment (please complete the following information):**
 - OS: Linux
 - Browser: Waterfox
 - Version of Browser: 56.2.7.1
 - Version of Raccoony: 1.2.2

**Additional context**

The filename does seem to be available within the page source, appearing as part of the "post to LiveJournal" code as well as in a section just after the "report submission" code.  Although these are for a thumbnail and would require the removal of a size reference, (daily_paint_2283__merit_badger_by_cryptid_creations_dd0ani1-150.png in the example case).

**Comment by Simon-Tesla** [comment]
Fixing {siteFilename} to go chasing after dA's changes in filename formats is not a high priority for me, especially since dA has been in flux lately. Also, {siteFilename} has never been about providing a consistent format, it's about providing the filename (if any) that the scraper found while trying to get an image to download, and it depends on the site to provide that consistency, which dA has very much not been providing. I'd suggest using the default format if you want something more consistent.
