### ISSUE TITLE
FA wrong submissionId  for downloaded objekts

### ISSUE THREAD

**Issue by fenpaws** [Simon-Tesla/RaccoonyWebEx#44]
**Describe the bug**
Wrong submissionId on FA

**To Reproduce**
1. Go to furaffinity.net
2. Click on any picture
3. Download the picture with Raccoony
4. take the id from the downloaded picture and paste it here https://www.furaffinity.net/view/**ID**/

**Expected behavior**
The submissionId of furaffinity images should be the one in the URL, so you can use the id to find all images on FA. 
As it is handled momentarily, the ID is taken from the suffix of the image.

**Environment (please complete the following information):**
 - OS: Windows, Mac, Linux
 - Browser: Firefox]
 - Version of Browser: 71.0b9
 - Version of Raccoony: 1.2.2

**Comment by Eupeptic1** [comment]
The ID is currently set [here](https://github.com/Simon-Tesla/RaccoonyWebEx/blob/master/app/plugins/furaffinity.ts#L28).  The comment on [line 22](https://github.com/Simon-Tesla/RaccoonyWebEx/blob/master/app/plugins/furaffinity.ts#L22) implies that the ID is the same in the path and the filename, but from looking at some submissions, they don't always match.

In other words, the download URL is more like
`https://d.facdn.net/art/[username]/[id1]/[id2].[username]_[origfilename].[ext]`.

id1 and id2 can be slightly different numbers.  I have seen them be equal, and I have seen id1 be as much as 475 or as little as 1 larger than id2.  I'm not sure if id1 can be smaller than id2.  I have seen them differ on files uploaded before the new FA UI went into production about 2019-12-31, so I don't think it's related to the FA UI change.

**Comment by Eupeptic1** [comment]
I just tested this on FA.  Based on a sample size of 1, id1 and id2 are the same _if_ the user has never updated the original submission with a new file.  If the user does update the original submission, id2 stays the same as it was, but id1 changes.

Because of the way FA's submission ID numbers appear to work, I think that id2 will always be equal to or larger than id1, but I don't know if FA actually documents that or guarantees it.

I also don't know what the right action for Raccoony is, here.  I know that at least until the end of 2019, and possibly even still now, when you made a new submission to FA, it wasn't possible to upload anything larger than 1280x1280.  Artists that wanted to post things bigger than that always had to upload a reduced version first, and then update the submission with the full-sized version.  This would cause id1 and id2 to be different on most larger images on the site.

Details:

I made a new upload of a red square and the resulting download URL was

https://d.facdn.net/art/eupeptic/1583794297/1583794297.eupeptic_red-test.png

.  I then updated the submission with a green square and got 

https://d.facdn.net/art/eupeptic/1583794368/1583794297.eupeptic_red-test.png

; note that id2 stayed the same but id1 is slightly higher.

(FA also kept the original filename from my first upload, which probably isn't relevant here, but I figured I would note it.)

**Comment by Simon-Tesla** [comment]
The way this used to work and the behavior that I'm pretty sure this bug wants to fix is for the submission ID to match the ID in the *page* URL, not whatever IDs are attached to the image (e.g. for this submission URL `https://www.furaffinity.net/view/35105581/`, the submission ID would be `35105581`).

It happened that they used to match up, but I imagine that FA had to stop doing that in order to onboard cloudflare so that they can do cache-busting properly.

**Comment by Eupeptic1** [comment]
> for the submission ID to match the ID in the page URL, not whatever IDs are attached to the image 

That makes more sense, actually.  :)

I was just in the weeds of the FA plugin for other reasons and saw the comment that treated the two different IDs in the image URL identical.  I had seen examples where that wasn't the case, and I jumped to it being related to this bug.

Raccoony currently keeps track of one submission ID per submission.  Would anything good or interesting happen if it kept track of _both_ the "master" page/submission ID, and the ID for the image itself?

> It happened that they used to match up

I don't remember when FA changed this.  The oldest FA image that I have a bookmark for has an ID in the page/submission URL in the 900,000 range, but the ID in the image file URL is in the 1,196,000,000 range.  I bookmarked it in early 2010, but it was posted to FA in late 2007.  It's also possible that the page/submission ID and the image file ID actually matched when it was posted, and then FA migrated later, to the current situation where they don't match.

**Comment by Simon-Tesla** [comment]
I'm pretty sure they had to do it for cloudflare *and* they probably did a migration of old images to the new system just to make sure everything worked correctly, which likely changed the ID numbers on the images themselves. The old behavior definitely used to be that the submission ID was also in the image's filename though.
