### ISSUE TITLE
Download all new submissions

### ISSUE THREAD

**Issue by LTGM** [Simon-Tesla/RaccoonyWebEx#47]
**Is your feature request related to a problem? Please describe.**
Frustrated with manually saving and ych-spam, I don't have that much time lately so I want to automate it somehow (especially if you was away for a while and have like 3k updates)

**Describe the solution you'd like**
Option to download every picture that appears in my submissions on FA by clicking a button using save paths like artist-art/sketches, etc and remove the notification about that submission on FA, once downloaded (removal is not necessary)

**Describe alternatives you've considered**
Maybe as an alternative download submissions from artists I subscribed to by date (so I can download bunch of them starting from date x without downloading their whole gallery)

**Additional context**
If anyone knows how to do that please help/tell me

**Comment by Simon-Tesla** [comment]
I feel like fixing #35 would probably mostly address the use case here. Basically, you'd enable auto-download when viewing a submission, then open all of your submissions in tabs to download them. If this doesn't fit what you had in mind, please add a clarification.

**Comment by LTGM** [comment]
That may work but will put an additional stress on the system (especially ones with low amount of ram) not to mention their servers and may lead to a ban from FA I think. I still think that background downloading picture after picture with a little delay is a better idea

**Comment by Simon-Tesla** [comment]
The 'open all in tabs' feature has a built-in delay that keeps it from attempting to load all tabs at once, which should keep FA from viewing it as bannable traffic. Unfortunately, Raccoony needs to load the page containing the submission in order to figure out what file to download, so background processing isn't going to decrease the number of requests made to FA's servers.

I have some plans for making open all in tabs work and perform better, which combined with fixing the aforementioned bug should make that a reasonable solution. At the moment things have been hectic with work and I haven't had the energy to work on Raccoony, but I'm hoping to work on some of these issues in the near future.

**Comment by Simon-Tesla** [comment]
I'm going to go ahead and close this bug. The fix to #35 should address this use case. I don't see a compelling reason to try to do downloads without opening the submission in a tab as it adds more complexity that I'm not willing to take on at this point in time.
