### ISSUE TITLE
Enable re-download

### ISSUE THREAD

**Issue by AfxousaAjagara** [Simon-Tesla/RaccoonyWebEx#50]
**Is your feature request related to a problem? Please describe.**
Whenever I try to re-download gallary, it's already checked for download and unable to re-download artwork never again. I think 

**Describe the solution you'd like**
Adding option for re-download is enough I think.

**Describe alternatives you've considered**

**Additional context**

**Comment by Eupeptic1** [comment]
I have noticed that as long as a particular file is still shown in Firefox's download history, Raccoony will still consider the file as downloaded - the download button in Raccoony will say "Downloaded" and nothing happens if you click on that button.

If I go into Firefox's download history (Tools > Downloads in Firefox), delete the record of that particular file being downloaded, and then re-visit the image page, Raccoony offers the "Download" button again.

**Comment by Simon-Tesla** [comment]
If you use Firefox, Eupeptic's answer should give a good workaround. Restarting Chrome may also work for Chrome. If you have keyboard shortcuts enabled [Shift]+D should also force it to download, as will right clicking on the image and picking "Download with Raccoony".

That said, having the option to re-download right in the UI seems like a useful one.
