### ISSUE TITLE
changes to e621.net have partially broken Raccoony support

### ISSUE THREAD

**Issue by Sanicle87** [Simon-Tesla/RaccoonyWebEx#51]
**Issue Type: Bug**
Since recent changes have been made to e621.net, Raccoony fails to trigger on the home page and all searches. This breaks features such as "open all in tabs". The issue is not present on individual submission pages, so raccoony download, auto-fullscreen etc are still available.

Additionally, artist tags are no longer read properly, so e621 downloads are lumped into an "unknown" folder, rather than artist subdirectories (the expected behaviour).

**To Reproduce**
Visit e621.net and perform any search. Raccoony won't trigger on the resulting page.

**Expected behavior**
Raccoony should be available on search results pages throughout e621.net, as was previously the case. Artist info should be read and used to correctly sort downloads into folders.

**Environment**
 - OS: Windows 10 Pro Build 1909
 - Browser: Firefox 73.0.1 (64-bit)
 - Version of Raccoony: 1.2.2

_Edited on 12/Mar/2020 to reflect additional issues discovered since the e621 update._

**Comment by Eupeptic1** [comment]
I can confirm the same bug, with Raccoony 1.2.2 and Firefox Quantum 68.5.0esr, 64-bit, on Linux desktop.

## Analysis

The [query selector](https://github.com/Simon-Tesla/RaccoonyWebEx/blob/master/app/plugins/e621.ts#L72) currently used doesn't match the HTML anymore.  This probably happened when e621 updated their site considerably on about 2020-03-05.

## Possible fix

Changing that line to `let links: HTMLAnchorElement[] = querySelectorAll("#posts-container .post-preview a");` passes the smoke test; I get the raccoon-head logo again on gallery and search pages, and clicking "open all in tabs" appears to work.  Further testing to follow.

**Comment by Simon-Tesla** [comment]
I've also received a report that it no longer finds the artist tag correctly, so there's another thing to look at.

**Comment by Eupeptic1** [comment]
> I've also received a report that it no longer finds the artist tag correctly, so there's another thing to look at.

Can confirm.  Several of the metadata fields aren't being found, at least on a dozen or so images I tested.  Still on Firefox Quantum 68.5.0esr, 64-bit, on Linux desktop.  I am using Raccoony 1.2.2, but patched with 1) my recent pull request and 2) the querySelector change I noted above to the e621 plugin.

Fields that appear to still be working correctly: url, previewUrl, siteFilename, filename, extension, siteName, type, sourceUrl .

Fields that are broken:
`author`.  Always ends up as "unknown".
`description`.  Ends up as "", even for images that have a description.
`tags`.  Always ends up as the empty array, [].
`title`.  Ends up as null on the images I've loaded so far.  However, due to the nature of e621, I'm not sure the uploader always fills in the title that the image had on the source site, or if that's even possible.  I know a few artists post directly to e621 themselves, and those images may have titles; I need to find one like that for a test case.

I also noticed some other things, possibly unrelated to the site layout change:

1.  If you did a search on "foobar" to get a gallery of results, the gallery page includes the search term in the `<a>` links to the individual image pages, like https://e621 dot net/posts/1234?q=foobar and https://e621 dot net/posts/5678?q=foobar .  Raccoony uses these links when doing open-all-in-tabs, and if you save the metadata files for the individual images, they show up in the `sourceURL` field.  I'm not sure if this was the old behavior or not, but I could argue that those should be scrubbed, and `sourceURL` should be just https://e621 dot net/posts/1234 .  (URLs munged on purpose, but you get the idea.)

2.  If you turn on auto-download in Raccoony, and open-all-in-tabs on a gallery page on e621, you get a new tab for each image on the page (good), but not all of them auto-download (bad). This may be related to #35, or it may be something else.

**Comment by Eupeptic1** [comment]
I have revised the e621 plugin and tested it on a dozen or so images so far.  New code here: https://gist.github.com/Eupeptic1/40ba1c0fb77eb980c4ea14b1643f5e1c

This continues the action of the previous plugin of making a filename out of the first three tags.  However, if the artist is tagged, the artist's name will be the first tag.  This may lead to duplication in filenames, like "simon_mouse_rodent_by_simon.jpg".  This could be adjusted by juggling the order in which we look for the different classes of tags, or in other ways.

I've seen six classes of e621 tags so far (artist, copyright, character, species, general, meta), but there might be more.

If an image is blacklisted, the plugin will download the actual artwork, and not the "Blacklisted" placeholder image.  I think that is the correct action.

This code has a lot of logging statements in it.  Some of them could probably be removed after testing.

**Comment by Eupeptic1** [comment]
Some notes:

In cases where the tags might be ambiguous, e621 has tags like "CoolGuy1 (artist)" and "CoolDragon2 (character)".  The parenthetical things show up in the filenames generated by the plugin, like "coolguy1_(artist)_dragon_scalie_by_coolguy1_(artist).jpg".  Maybe we should detect those and strip them out.

In cases where the artist is not known, _and_ the image is not tagged with the "unknown artist" tag, the plugin just gets nothing (empty string) for the artist name, which I think gets mapped by the main part of Raccoony into a single underscore.  This leads to filenames like "12345_dragon_scalie_wings_by__.jpg".  NSFW example: https://e621 dot net/posts/1648500

**Comment by Simon-Tesla** [comment]
Again, thank you for looking into this. Would you like to submit a PR, or do you want me to grab the gist and do it myself? Or are you doing more testing?

**Comment by Eupeptic1** [comment]
I want to do more testing.  I started with it basically working on one image, but I looked at three more images and made two more code changes before I posted the gist.  It's been stable for a few more images, but I feel like it should be stable for longer than that before I inflict it on the world.  :D

Does e621 also let you post stories, music, movies/animations?  If so, I need to test it on those, too.

The reason I've been posting the gists is so you can look at the revised code, in isolation, and tell me if anything is obviously horribly wrong, like me misunderstanding what the members of I.Media do, or "the foo plugin also used to do it that way, but I had to change it, because of...", or if I've done something that might be O(n^4) sometimes, or like that.

When I submit a PR, that's me saying "I have tested this and I think it's reasonably likely to work well when widely deployed".  I'm not at that point with this code yet.

**Comment by Simon-Tesla** [comment]
Ah, understood. I just took a look at the file and overall it looks like your approach is sound. 

e621 supports WebM, MP4, SWF and ZIP (in addition to the usual JPG/PNG/GIF images). As far as I'm aware, it doesn't support stories or music.

I don't believe there are any other types of tags, though now that the tags themselves have a class on them, you might be able to get away with just using `.search-tag` as your selector for tags, without including the tag-list parent or the href attribute selector. The only reason that the selector used to be complex is because the links didn't have a convenient class attached to them before.

Another thought for generating the filename, given that we already have the author(s) elsewhere would be to separate the artist list tags out from the rest and then pick the top 3 from those. Keep in mind that a piece can have more than one artist tag listed.

The callback for getting the submission ID in the getPageLinksFromAnchors() call looks like it's grabbing the wrong part of the URL, presumably because e621 doesn't have the tag slug in the URL anymore, it just has the ID. Should be able to just remove one of the urlparts.pop() calls though.

**Comment by Eupeptic1** [comment]
I am working on it some more this afternoon/evening.

> e621 supports WebM, MP4, SWF and ZIP (in addition to the usual JPG/PNG/GIF images).

I found some SWF, WebM, and animated GIFs, and the plugin DTRT for those.  Do you have any links handy for submissions with MP4 or ZIP types?  I haven't found any of those so far, but I'm still looking.  (Do they possibly convert MP4 to WebM after upload?)

I also found https://e621.net/help/supported_filetypes , which doesn't mention ZIP, but it does says APNG is supported.  I think there are about five APNGs on the Internet, but I haven't been able to find one on e621 yet.  :)

My interest with the "animation" types is to make sure the plugin is getting the actual animation file, and not the thumbnail, just because that has been a bug for other plugins in the past.

> I don't believe there are any other types of tags,

Breaking news: they added one last week!  "Lore" tags.  It has its own class, similar to the other types of tags.

> you might be able to get away with just using .search-tag as your selector for tags, 

I tried this and it works.  In one way, it works even better than naming each type of tag separately, because it automagically started picking up the new lore tags.  The way I initially did it, with the six types searched for separately, would miss the lore tags.

> separate the artist list tags out from the rest and then pick the top 3 from the non-artist tags.

I made a change to do this and it basically works.  It's a little bit inefficient, because I do one query (with just `.search-tag`) to get all of the tags, and then a separate query (with the six other types named explicitly) to get the non-artist tags.  I feel like I should be able to query just the artist tags, query just everything else, combine those two arrays for the main tag list, and then work with the everything-else array to generate the file name.

On the other hand, having to name the parents explicitly to get the non-artist tags makes it more brittle against future new tag types.  Googling tells me that `:not` in the selector may be my friend here.

> Should be able to just remove one of the urlparts.pop() calls though.

You were right.  Now I am setting `submissionID` to a string like '12345?q=foobar'.  The main part of Raccoony seemed to accept that OK, but I am playing with also trimming off the query, to just have it be '12345'.

**Comment by Eupeptic1** [comment]
I have revised the plugin further and tested it on half a dozen or so images.  New code here: https://gist.github.com/Eupeptic1/7e158250b2d9a1ac1d8cf14b564e0467

Points of note:

I changed the way the artist parsing works to better detect when the artist is unknown.  If the image is tagged "unknown artist" on e621, or if there is no artist tag at all, the artist gets set to "unknown artist".  That way, all such images end up in `raccoony/e621/unknown_artist` when downloaded.

For the tags, I get the artist tags as one list, and everything else as another list.  I combine the two lists to send to the rest of Raccoony, and I use the first three tags in the everything-else list to build the local filename.

I added a comment that "title" is not supported at all, because e621 apparently doesn't support it.  I also added a comment about this plugin not having `isSubmissionPage()`.

In `getPageLinkList()`, I scrub the query part (`?q=foobar`) out of the URLs.  That has a couple of effects: 1) the queries don't show up in the `sourceURL` entries in the metadata files anymore, which is what I was after, and 2) if you use open-all-in-tabs in Raccoony, the search box for each submission on e621 is no longer populated with the search terms that found you that image.  I'm not sure if 2 is good or not; some users might want those terms to be populated, so they can refine their search from the individual submission page.

Also, to do the scrubbing, I am directly modifying the page, which feels slightly naughty.  I tried a couple of different ways to operate on a _copy_ of the HTMLAnchorElement[] array, but I couldn't quite figure out how to make that work.

I plan to test this on some more images.  If you find a submission that is MP4, ZIP, or APNG , let me know the URL, so I can test against those.

**Comment by Simon-Tesla** [comment]
Hm, I'm not sure how worth it it is to scrub the search parameter. If we want to scrub the metadata, I'd rather do it on the `getMedia()` side by setting `I.Media.sourceUrl` to the URL we want to save with the metadata and then make the change to siteActions.ts to use that instead of `window.location.href` if it is present. That way we aren't compromising site functionality. Whatever we do we should *not* alter the DOM. (The right way to do what you're doing would be to operate on the list array we get from `getPageLinksFromAnchors()` instead of the link elements themselves.)

You can do a search by filetype by using "type:[extension]", but having done that I didn't find any of those files either. Might be that they're allowed for upload but they transcode them to WEBM or crack the zip open to use as a source for multiple submissions.

**Comment by Simon-Tesla** [comment]
Also, efficiency-wise, we're never operating on particularly large lists, and we're not doing things that'd cause a DOM repaint, which is the real perf killer in JS.

**Comment by Eupeptic1** [comment]
I am working on this some more tonight.  My goal is to get it to a pull request in the next day or two.

The reason I wanted to scrub the search parameter is specifically because it shows up in the URL in the metadata file.  I don't always want to be reminded of what search terms I used to find a particular image.  :D  Also, I don't think any of the other plugins save the search terms that way, so it seemed weird to me that the e621 plugin does.  On the other hand, most other sites' search functions aren't as aggressively RESTful as e621's.

If I can't correctly scrub the search parameter without modifying the main part of Raccoony, I'll just leave it in there.  I feel like the changes should remain contained in the plugin code.

> Whatever we do we should not alter the DOM.

I *knew* that felt wrong.  I will fix that, if nothing else.

On efficiency, I know that `premature optimization = sqrt(evil)`.  On the other hand, I think e621, by its nature, tends to have a lot more tags per submission than most other sites that Raccoony supports.  As soon as I decide that pulling the tag list twice is not that big a deal, and code that into the plugin, my concern is that some joker is going to turn off the delay-loading function, do an "open all in tabs" on 100 images, and then complain that their browser fell over and died.  :)

**Comment by Simon-Tesla** [comment]
Oh, I get why you'd like to scrub the search parameter, my point is to scrub it on the side where we're downloading stuff in the `getMedia()` side of things if we do it at all. We're not generating metadata files until that point. If you want to make the change I suggested on the plugin side, I can provide the fix on the main codebase side, but I'd strongly prefer that we didn't change the URLs returned by `getPageLinkList()`.

Not super concerned about perf for this; just opening that many tabs at once is going to massively dwarf the extra JS execution time in the browser, given how much work it's going to be doing. Also, the way it's currently coded, it's impossible to use a delay of less than 1 second for open all unless they fork the code. While it's currently not made explicit in the UI that this is the case, I might do that eventually, just from the standpoint that it's extremely no bueno to hit a website like that and I don't want to support that sort of thing directly in the extension. If someone decides to fork and remove it, then the perf characteristics of the extension are on them at that point :P

**Comment by Eupeptic1** [comment]
I got over my fear of modifying siteActions.ts and did the change as you suggested; it seems to be working for e621, but I still need to check other sites to make sure I didn't break them.

I only changed `getMedia()`; I didn't change `getMediaForSrcUrl()`, mostly because I haven't chased down the conditions under which the latter function gets called.

My change looks like this:

```javascript
            // If a plugin explicitly set sourceUrl, use that; otherwise
            // use window.location.href.  As of 2020-03, only the e621
            // plugin sets sourceUrl, so it can provide a URL without the
            // search terms appended.
            const sourceUrlNotProvided = !media.sourceUrl;
            if (sourceUrlNotProvided) {
                media.sourceUrl = window.location.href;
            }
```

I also found another case of the `og:title` tag on e621, so I fixed the plugin to handle that.

I'm also working on version 0.00000000001 of automated test, but I'm not going to let that get (too much) in the way of finishing the work on the e621 plugin.  :D

**Comment by Simon-Tesla** [comment]
That should work. :)
Also very curious about the automated testing; haven't really done much investigation on what it'd take to do that in the context of Raccoony.

**Comment by Eupeptic1** [comment]
Gist of what I currently have here: https://gist.github.com/Eupeptic1/cb5bd6794f27c9a8265048d8bf44d73c

I have tested this on e621, FA, and Weasyl so far, and it seems to DTRT; mostly I was making sure that my change to siteActions.ts didn't break `sourceUrl` on sites other than e621.

I will kill the commented-out section in `getPageLinkList()` (where I was trying to scrub the search terms) before this goes up to a PR.

Plan: Dogfood for the next day or two, then create PR.  Immediate plan: sleep.  :)
