### ISSUE TITLE
only getting unknown artist on e621

### ISSUE THREAD

**Issue by 99spooner** [Simon-Tesla/RaccoonyWebEx#73]
**Describe the bug**
whenever i try to go and download from e621 the artist folder and the filename both have unkown_artist

**To Reproduce**
1. go to e621
2. Click on any post
3. download it
4. you get the error i described above

**Expected behavior**
what i expect to happen is for the folder and filename to have the right artist for example:
the default settings: 00001_nintendo_by_99spooner.png
my own settings: 00001.99spooner.png

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version of Browser: Version 86.0.4240.198
 - Version of Raccoony: 1.2.3

**Additional context**
Add any other context about the problem here. Include:
-none of the post that i downloaded from had their tag as unkown_artist
-other sites (FA for example) seem to still work fine

**Comment by Eupeptic1** [comment]
I am seeing the same thing.

I don't visit e621 as often as other sites that Raccoony supports, but this seems to have been happening at least by 2020-10-26; a few images I downloaded on that day were tagged unknown_artist, even though e621 is showing an artist for them.  Also, everything I've downloaded since that day (100+ images) have all been tagged unknown_artist, and I'm pretty sure e621 has the artist for some of them.  More analysis to follow.

**Environment**

Debian 9.13 on amd64/x86_64, desktop
Firefox 78.5.0esr, 64-bit
Raccoony 1.2.3

**Comment by Eupeptic1** [comment]
**Analysis**

The e621 plugin currently looks for one of the meta tags in the page header to get the artist:

`let usernameElt = querySelector('meta[name="og:title"]');`

When this runs, though, it thinks usernameElt is null.

The comments (don't debug the comments) indicate that when that code was written, the meta tag was of the form `<meta name="og:title" content="[the title]">`

Looking a live page on e621, there is still a title meta tag, but now it's a property, instead of a name:

`<meta property="og:title" content="[the title]">`

So maybe changing that query to look for a property instead of a name will work.

There's also an argument that this is the wrong way to do it; later in the plugin, we also grab the artist's name(s), if available, out of the tags.  Maybe we should just get the name from there.

TBD: I know e621 allows pictures to be tagged with more than one artist name; is there a difference between how they handle that in the meta tag, vs in the main tags?  If so, which one should Raccoony use?  If there is more than one artist, do we want to use the first one, or concatenate all the artist names, or something else?

**Comment by Eupeptic1** [comment]
Changing line 74 of e621.ts to

`let usernameElt = querySelector('meta[property="og:title"]');`

works 100% of the time... on a sample size of 1.  :D  More testing to follow.

**Comment by Eupeptic1** [comment]
Tested on eight images total, including ones that really are unknown artist (no artist tag on e621), and ones that are collaborations of two artists, and it seems to work correctly.

If you agree with this change, I can submit a pull request.  If you think I should rework where the plugin gets the artist tag (per the above), let me know.

**Comment by Simon-Tesla** [comment]
That would be wonderful, thanks

**Comment by Eupeptic1** [comment]
Pull request is go.

I had to do some git dances, because I previously had some stuff on my master (for Pixiv) that I didn't want to include in this pull request.  I think I successfully moved the Pixiv stuff to another branch in my repo, got my master branch to be a "clean" copy of your master branch, and then applied just the e621 patch.  I am still unsure about the long list of commits in this pull request, but the only file that has changed is the e621 plugin, so I *think* I created it correctly.

**Comment by Simon-Tesla** [comment]
Looks like you got it right to me. And yeah, it's pretty much always a better idea to do major work on a different branch from master in any case. You should be able to create PRs from any branch you want, so the workflow is usually to keep master synced with the base repository, and then branch off of master to do work you intend to submit as a PR.
